### ISSUE TITLE
string类型的diff方法会出错

### ISSUE THREAD

**Issue by shanhuang94** [didichuxing/collection#1]
![image](https://user-images.githubusercontent.com/37739323/91316916-f9a6a400-e7eb-11ea-9794-a8a91fa28b43.png)

可以看到原来的逻辑是有问题的，返回数组会把原来的数组元素放到结果数组里面，具体应该是在这里实现的
![image](https://user-images.githubusercontent.com/37739323/91316286-3920c080-e7eb-11ea-81b9-29173d366873.png)

如果使用注释掉的代码就没有问题了

**Comment by jianfengye** [comment]
最新代码ok了
