### ISSUE TITLE
考虑支持split吗？

### ISSUE THREAD

**Issue by suitingwei** [didichuxing/collection#2]
类似laravel collection的split，将slice切片。

split()
The split method breaks a collection into the given number of groups:

$collection = collect([1, 2, 3, 4, 5]);

$groups = $collection->split(3);

$groups->all();

// [[1, 2], [3, 4], [5]]

**Comment by jianfengye** [comment]
这个可以支持的，我考虑下如何增加

**Comment by jianfengye** [comment]
你可以参考： https://github.com/jianfengye/collection
